name: Eslint

on: [push]

jobs:
  fix:prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Yarn Install
        run: yarn install
      - name: Run Prettier
        run: yarn fix:prettier
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
